# Simple workflow for deploying static content to GitHub Pages
name: Build and push docker image

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: 'api'
  cancel-in-progress: true

jobs:
  docker:
    defaults:
      run:
        working-directory: ./app
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ${{defaultContext}}:apps
          push: true
          tags: christian-bick/edugraph-api:latest
